### ISSUE TITLE
[BUG]  many errors poping up

### ISSUE THREAD

**Issue by jakesakiller** [qbcore-framework/qb-doorlock#107]
im getting a couple errors with the script, ive tried replacing certain files still cant fix it
![Ek0ymZ6](https://user-images.githubusercontent.com/95553416/176987335-292f41ea-1cb5-4b52-8fba-b207b532392f.png)

https://i.imgur.com/Ek0ymZ6.png

**Comment by PatalJunior** [comment]
Same for me

**Comment by PatalJunior** [comment]
Similar issues regarding localization
