### ISSUE TITLE
[BUG] Door lock dissapearing

### ISSUE THREAD

**Issue by skrubzilla** [qbcore-framework/qb-doorlock#109]
Door locks are not staying on doors. Suddenly a lock will disappear for everyone and the door wont be lockable comes back after script reboot 60+ people in server

**Comment by Mat00t** [comment]
I find the locks come back after a little bit of time, but definitely have noticed this since updating doorlocks.

**Comment by FrequencyRoleplay** [comment]
this has been a reoccurring issue. I have seen for myself and gotta reports of door locks not showing .  A restart of the resource resolves it.  came here to see if theres been any recent updates to help resolve this. Has anyone tried any code edits and care to share a snippet?

**Comment by Powsa** [comment]
Same issue here

**Comment by FrequencyRoleplay** [comment]
solution was to use Ox_doorlock
and importing your qbdoorlock config into doorlocks database. 

works the way its suppose to.

**Comment by Rtextbook** [comment]
> solution was to use Ox_doorlock and importing your qbdoorlock config into doorlocks database.
> 
> works the way its suppose to.


question, so im noticing its holding the state unless a player is near it. so like if you get away from the locked door. then run or drive up quickly it takes time for the state and lock to sync it would seem. is there no fix to  the server focusing and keeping the state of it in sync?
