### ISSUE TITLE
[BUG] Newdoor Menu is popping up as mini text boxes instead of fancy menu window

### ISSUE THREAD

**Issue by Wildeman13** [qbcore-framework/qb-doorlock#112]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.
Not sure if this is a bug, conflicting mod, or some config I am missing in here, but when I go to create a new door using /newdoor, I get the menu in the upper left corner in a super simple and sometimes hard to read format instead of the large menu window that I have seen when this mod was showcased. 

See https://i.imgur.com/QJ2Xw4D.png

Is there a config I am missing that is causing this? 

My install is from Zap-Hosting txAdmin template deploying QB-Core and my qb-doorlock appears to be up to date. 

**To Reproduce**
1. Open "chat" T window, type /newdoor
2. See error in upper left corner as seen in imgur link

**Expected behavior**
Fancy menu as seen in demo videos on YouTube - https://www.youtube.com/watch?v=x9i6gXaLGxg&t
https://i.imgur.com/2A55UtM.png

**Screenshots**
https://i.imgur.com/QJ2Xw4D.png - How I see it

https://i.imgur.com/2A55UtM.png - How I expected to see it

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] - Confirmed matches current GIT repo
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] Mostly qb-core "package" from Zap Hosting
 - Have you renamed `qb-` to something custom? [e.g. yes/no] no

**Additional context**
I can provide a list of mods if needed. I have done minimal config changes as this is simply a sandbox/learning server.

**Comment by Dan4ou** [comment]
Just change qb-input to the latest and it will be okay, bro! Hope I helped you!
qb-input - https://github.com/qbcore-framework/qb-input
