### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by kokorog** [qbcore-framework/qb-doorlock#113]
Can i make one door to can be opened by two jobs? like police and ambulance

**Comment by GetBackJames** [comment]
> Can i make one door to can be opened by two jobs? like police and ambulance

Yes you can just go into the lua for the doorlocks you want to edit and just add a second job to whatever's there.

**Comment by YG0007** [comment]
Yes you can do it by changing
authorizedJobs = { 'police', ambulance } in the config
