### ISSUE TITLE
/Newdoor opens the menu but is not showing the doors to select [BUG]

### ISSUE THREAD

**Issue by BilZz03** [qbcore-framework/qb-doorlock#116]
So, it was working fine until now, when I try to create a new door with /newdoor command the menu comes up and after filling it and selecting create doors, it tells me to create the door but when I point at the door, the door is not highlighting. This is for all the doors.

No errors are showing up in both console and F8

Updated today (was trying to see if update would fix and it didn't)

![doorlock issue](https://user-images.githubusercontent.com/111319696/184727655-c26d1681-8f5b-4a22-8a73-7b94cb59d9a9.png)

**Comment by DeNtrlPredator** [comment]
I have started having this issue as well

**Comment by DeNtrlPredator** [comment]
> 

Unsure of the original person. But in my server yes I am using MLOs and the issue is present

**Comment by mikefromdot** [comment]
Also having this issue, pretty sure something was changed on the fivem side as previous versions of this script and the script that it was based off of do not work either.

**Comment by itsHyper** [comment]
I have this issue aswell, /newdoor hasn't worked since nui_doorlock... I think its a script conflicting because it works on a default QBCore server... and my server is the exact same just my custom stuff added

**Comment by Dadbodofthunder1** [comment]
@BilZz03 did you get this figured out literally the same exact thing happening to me

**Comment by DeNtrlPredator** [comment]
> @BilZz03 did you get this figured out literally the same exact thing happening to me 

I would recommend switching to ox_doorlock. It's optimized, has a up where you can create, edit delete existing doors. We switched and it's a way better experience.
