### ISSUE TITLE
[BUG] Gabz Cell doorlocks are not functioning properly

### ISSUE THREAD

**Issue by masutto** [qbcore-framework/qb-doorlock#121]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

Hey Team, I just installed the latest qb-doorlock from this github and went to test out the mrpd cells and the doors wont stay shut when says locked, and vice versa. 

**To Reproduce**
1. Go to 'MRPD Cells'
2. Click on 'E-Lock/unlocked'
3. Watch doors not operate property

**Expected behavior**

Cells are supposed to function when locking the cell door and actually locks and vice versa

**Screenshots**
If applicable, add screenshots to help explain your [problem.]
[https://streamable.com/qnu6xx](url)

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] 
                     Today
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
             Qb-target
 - Have you renamed `qb-` to something custom? [e.g. yes/no]
                        No
**Additional context**

I have tried to remove the mrpd file out of the configs file just to test and that doesnt work at all. At this point i cant think of anything else

**Comment by Wafflzdev** [comment]
Are you using a custom MLO?  Also, check the coordinates in qb-doorlock/config to make sure the door you are locking/unlocking matches where the physical door is.

**Comment by masutto** [comment]
i've done that, still isn't working

**Comment by Wafflzdev** [comment]
I believe that script is out of date, but you should check with the author.  Also, I am not able to click on the link you posted as the screenshot.  You need a weapon with no ammo to target the door.  You can use https://docs.qbcore.org/qbcore-documentation/qbcore-resources/qb-doorlock for questions on how to configure a door.

**Comment by Leslija** [comment]
Looks like one of door distances is too big.

**Comment by masutto** [comment]
ok so i am using gabz-doorlock that came with his maps. i threw his mrpd in to the qb-doorlock/configs folder and refreshed/restarted the doorlock script

i am still having the same issue as i just downloaded straight off this github, Code-download and replace qb-doorlock script in my qb folder and added the config from gabz doorlock folder

**Comment by Leslija** [comment]
I do not have the gabz-doorlock, but I sugesst you to do it manually.. As the coordinates might differ.
