### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gbandzz** [qbcore-framework/qb-doorlock#124]
**Describe the bug**
set a lock then it says locked but doesn't say to hit E to unlock or anything just stuck locked wasn't happening before but then randomly started

**To Reproduce**
1. Set a lock on the door
2. set it as locked 
3. try to unlock 
4. nothing happens 

**Expected behavior**
For it to say "E locked" then click E and the door will unlock

**Screenshots**
![image](https://user-images.githubusercontent.com/95923239/190838815-59b9e36d-6762-4bf0-b7dc-ae42e77a4959.png)

**Questions (please complete the following information):**
 - When you last updated yesterday ]
 - Are you using custom resource? which ones? Vespucci PD
 - Have you renamed `qb-` to something custom? no

**Additional context**

**Comment by ChristianBDev** [comment]
@gbandzz Did you allow the police or set `authorizedJobs = { 'police' }` in the config.lua within that door?
