### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Andey2021** [qbcore-framework/qb-doorlock#141]
When creating doors i get a error in tx admin console only no errors in game 
[  script:qb-doorlock] SCRIPT ERROR: @qb-doorlock/server/main.lua:227: /home/zap1044274/g539505/gta5-fivem-txadmin/QBCoreFramework_CC2F53.base/resources/[qb]/qb-doorlock/configs/mrpd.lua: Permission denied

**To Reproduce**
1. start server
2. try and create door
3. see error

**Expected behavior**
Be able to create the toor

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: Today
 - Are you using custom resource? which ones? [ qb-target]
 - Have you renamed `qb-` to something custom? [no]

**Additional context**

**Comment by WadeDanger** [comment]
when i want to create a door it seis theat i dont have premissions
