### ISSUE TITLE
[Suggestion/Improvement]

### ISSUE THREAD

**Issue by meistroburger** [qbcore-framework/qb-doorlock#18]
Create a way to open door locks with a certain item (like a "key" item from shared.lua).  It will be much easier If you've locations as Hotels, Motels or Houses.

**Comment by evanillaa** [comment]
nice idea

**Comment by azwoodd** [comment]
With this function is it possible to have the option of multiple items? Not all used at the same time but lets say there should be 3 items that if having just one of the 3 you would still gain access, can’t seem to get it to work
