### ISSUE TITLE
Suggestion: Reloading QB-Doorlocks

### ISSUE THREAD

**Issue by P4R4NORM4L** [qbcore-framework/qb-doorlock#25]
Reloading the qb-doorlocks script does not take in effect the job you currently have, you need to re-log in order for it to detect what job you have. If it could check your job on script reload, it would be easier to code the locks instead of logging off and on every time.

Also What MLO's have you based your door locks on? It seems to me like the MLO's I have installed are quite different from the location of the door locks.

**Comment by meistroburger** [comment]
You could simply type /logout or go to your house and "Log Out" (Character Switcher) en go back in
