### ISSUE TITLE
[BUG] Sliding Gates Do Not Lock

### ISSUE THREAD

**Issue by lildiznick** [qbcore-framework/qb-doorlock#28]
There is an issue where the text will say that the sliding gates such as at the sally port at the prison, and the back gate at MRPD are locked, but they still open. This seems to happen with locked garage doors as well.
![FiveM - WWCRP qbCore RP Server 9_27_2021 1_26_14 AM](https://user-images.githubusercontent.com/68559172/134855291-4b24c200-bc12-4da4-84eb-bcdb8ae09e2e.png)

**Comment by xCoryux** [comment]
Hello good,

You have to find the coordinates of that door and also the name of the door prop. Then in the config you look for the door by the coordinates and in:

objName = 'hei_v_ilev_bk_gate2_pris',

You put the name of the correct door prop and it should work. Normally when you put a custom map, the creator leaves a txt with the instructions.

**Comment by lildiznick** [comment]
I've done all of that for the custom maps and still nothing. Got the proper prop id using the delete laser and searching out the hash online. It doesn't even work out at the prison at those default sally port gates or that sliding gate behind mission row in it's sally port area.
