### ISSUE TITLE
Out of the box doesn't work.

### ISSUE THREAD

**Issue by Duguayster** [qbcore-framework/qb-doorlock#32]
Just downloaded and installed this to the server, by default the jail gates are locked, was able to roll up to them and they opened even though it stated they were locked.

**Comment by Duguayster** [comment]
thanks for the reply.

**Comment by GhzGarage** [comment]
Can you try this one? https://github.com/qbcore-framework/qb-doorlock/tree/c9975b38efac81443914e8f5ad453bd1af534b70

**Comment by scrubh** [comment]
@GhzGarage Kak this one u posted works good no desync
