### ISSUE TITLE
tried the latest version

### ISSUE THREAD

**Issue by killerpoedel** [qbcore-framework/qb-doorlock#34]
![image](https://user-images.githubusercontent.com/26230401/138195823-b716e7f3-91e4-41f0-8a0f-b776f71b23fa.png)
i got this trying to use latest version 

how can i fix this issue
and great respect to you guys for coding this amazing script 🥇

**Comment by HellraiserTwo** [comment]
Hello, @killerpoedel 
Are you running the latest qb-core version?

**Comment by killerpoedel** [comment]
@HellraiserTwo no we have not
