### ISSUE TITLE
tooo slow

### ISSUE THREAD

**Issue by GeekHamza1** [qbcore-framework/qb-doorlock#38]
guys i just updated qb-doorlock but its look like the script is too low , i mean when i go faster to a locked door  , the door is open after a sec its locked  and  print Locked

**Comment by Chxttr** [comment]
> guys i just updated qb-doorlock but its look like the script is too low , i mean when i go faster to a locked door  , the door is open after a sec its locked  and  print Locked

How I fixed it, is by changing the citizen.wait(1000) to (500) in the citizen.createthread
