### ISSUE TITLE
Doors not locked

### ISSUE THREAD

**Issue by SharkyFP** [qbcore-framework/qb-doorlock#66]
So there is an error where the locked door isn't locked but after like few seconds it gives you the option "Locked"
There aren't any errors

**Comment by BerkieBb** [comment]
When does this happen?

**Comment by SharkyFP** [comment]
> When does this happen?

This happends when I spawn on the server if I'm near the door.
Sometimes it happends when using /tpm and teleport close to door.

**Comment by BerkieBb** [comment]
Try this PR https://github.com/qbcore-framework/qb-doorlock/pull/67

**Comment by SharkyFP** [comment]
Will test it tomorrow if it still occurs. Changed the client with pr.

**Comment by BerkieBb** [comment]
I've gotten the report that it still doesn't work after the PR
But I've got a repro now, putting it here

Log out using F8 -> quit next to a door which is registered in the doorlock
Then log back in using last location

**Comment by sandunisuru** [comment]
I have fixed this. Can I send a PR with it

**Comment by SharkyFP** [comment]
I noticed that it wasn't only happening with connecting to the server and spawning next to the door, but also when tp-ing to cords of the door.

**Comment by BerkieBb** [comment]
It should be fixed with #79
