### ISSUE TITLE
qb-prison and qb-bankrobbery Doors No Longer Working.

### ISSUE THREAD

**Issue by txdaniel55** [qbcore-framework/qb-doorlock#68]
The Version 2 update has broken the function for unlocking the prison gates, and any bank-robbery doors that use items to unlock the gate/door.

**Comment by BerkieBb** [comment]
It didn't break them, they just aren't updated to the new event, that needs to be done

**Comment by Ziopeppettw** [comment]
when I enter in the bank of paleto from this error in the console :
[  script:qb-doorlock] SCRIPT ERROR: @qb-doorlock/server/main.lua:7: attempt to index a nil value (field '?')
[  script:qb-doorlock] > handler (@qb-doorlock/server/main.lua:7)

**Comment by BerkieBb** [comment]
Is your qb-core updated along with qb-doorlock?

**Comment by Ziopeppettw** [comment]
yes

**Comment by BerkieBb** [comment]
https://github.com/qbcore-framework/qb-prison/pull/58
Here is the PR to fix the prison doors

**Comment by Ziopeppettw** [comment]
I just updated the script, now it gives this error:
[  script:qb-doorlock] Error parsing script @qb-doorlock/server/main.lua in resource qb-doorlock: @qb-doorlock/server/main.lua:18: syntax error near '+'
[    c-scripting-core] Failed to load script server/main.lua.
[ citizen-server-impl] Started resource qb-doorlock

**Comment by BerkieBb** [comment]
https://github.com/qbcore-framework/qb-bankrobbery/pull/66
Here is the PR for bankrobbery

**Comment by BerkieBb** [comment]
> I just updated the script, now it gives this error: [ script:qb-doorlock] Error parsing script @qb-doorlock/server/main.lua in resource qb-doorlock: @qb-doorlock/server/main.lua:18: syntax error near '+' [ c-scripting-core] Failed to load script server/main.lua. [ citizen-server-impl] Started resource qb-doorlock

Download it again and don't edit anything, also make sure your artifacts are updated

**Comment by Ziopeppettw** [comment]
I always get this error: Error parsing script @qb-doorlock/server/main.lua in resource qb-doorlock: @qb-doorlock/server/main.lua:18: syntax error near '+'

**Comment by Ziopeppettw** [comment]
ok my name Tonict17
