### ISSUE TITLE
[SUGGESTION] Raycast General Interaction

### ISSUE THREAD

**Issue by izMystic** [qbcore-framework/qb-doorlock#72]
Make general door interaction use raycasting to get what model your looking at, and only lock/unlock that one

**Comment by PeeganKreece** [comment]
I've managed to do this with nui_doorlock but was having major issues with crashing when loading into the server. I'll try to recreate sometime when I get around to help fixing the other issues with qb-doorlock.

**Comment by ItsANoBrainer** [comment]
Coming with https://github.com/qbcore-framework/qb-doorlock/pull/79
