### ISSUE TITLE
script error couldnt solve

### ISSUE THREAD

**Issue by clayhack010** [qbcore-framework/qb-doorlock#78]
this is the error Error loading script server/main.lua in resource qb-doorlock: @qb-doorlock/server/main.lua:272: attempt to index a nil value (global 'Lang')
[  script:qb-doorlock] stack traceback:
[  script:qb-doorlock] 	@qb-doorlock/server/main.lua:272: in main chunk
how can i solve this please

**Comment by BerkieBb** [comment]
You need an updated qb-core
