### ISSUE TITLE
IndexSizeError for volume

### ISSUE THREAD

**Issue by SemperCertusetFidelis** [qbcore-framework/qb-doorlock#80]
When you stand in the middle of the door and toggle the lock, the sound reaches a value that is above 1.  Cause when dividing by a number lesser then 1, you get a value greater then the one you were dividing.

![image](https://user-images.githubusercontent.com/98713571/155897679-d4a7a2d1-3adf-4bc1-b5ab-635fa303a100.png)

So for my self I found a fix, but I'm not too confident in my JS skills so let me post it in here instead of making a pull request.

qb-doorlock/html/app.js:71

`        playAudio(data) {`
`            var volume = (data.audio['volume'] / 10) * data.sfx`
`            if (volume > 1.0) { var volume = 1.0; }`
`            if (data.distance !== 0 && data.distance >= 1.0) { var volume = volume /= data.distance; }`
`            const sound = new Audio('sounds/' + data.audio['file']);`
`            sound.volume = volume;`
`            sound.play();`
`        }`

**Comment by BerkieBb** [comment]
It's because the sound changes with the distance you're from it and also changes depending on your volume settings

**Comment by SemperCertusetFidelis** [comment]
Yeah so when standing somewhat in the door I assume the distance is somewhere between 0 and 1.

So when the volume setting is 0.7 and the distance is 0.5, you get this error.

**Comment by BerkieBb** [comment]
the distance can be upto 15

**Comment by BerkieBb** [comment]
Well actually it can be higher depending on the max distance set for the door

**Comment by BerkieBb** [comment]
I think just moving the if statement down that sets the volume to max is good enough

**Comment by SemperCertusetFidelis** [comment]
That works too to stop the error. I just thought the volume had to be within 0 and 1/

**Comment by SemperCertusetFidelis** [comment]
@BerkieBb I made a PR

**Comment by BerkieBb** [comment]
I see it, you can close this then I'll review the PR
