### ISSUE TITLE
Server starts with doors unlocked

### ISSUE THREAD

**Issue by CalzerB** [qbcore-framework/qb-doorlock#82]
Great script! However my doors are unlocked when the server restarts, even turning autolock on, it will not auto lock until I have locked / unlocked it once. 

**EDIT**

So it works fine, but the issue is that when you tick the locked tickbox when doing /newdoor, it wont add "locked = true" so it needs to be added manually, so other than that everything is mint!!!

**Comment by sandunisuru** [comment]
I have a fixed for that. Sending a PR

**Comment by BerkieBb** [comment]
You need to update qb-input for that to not happen
