### ISSUE TITLE
Need Update

### ISSUE THREAD

**Issue by sekem1000** [qbcore-framework/qb-doorlock#83]
The multicharacter works fine for qb-doorlock defult but some player are able to hop in realquick but there are many player who can't !

**Comment by BerkieBb** [comment]
What?

**Comment by ItsANoBrainer** [comment]
Provide a reproduction or actual steps to the problem.

**Comment by KingRyuShin** [comment]
@BerkieBb @ItsANoBrainer Sometime the distance check doesn't work, you can run toward the doors and you can go through it even though it is locked.

**Comment by BerkieBb** [comment]
Did you update your qb-doorlock to the newest?

**Comment by ItsANoBrainer** [comment]
Provide repro and verify install and updates.
