### ISSUE TITLE
[BUG] Fix test feature doesnt work properly

### ISSUE THREAD

**Issue by PeeganKreece** [qbcore-framework/qb-doorlock#84]
When creating a new door then opening the new config file and changing the doors from: 
``
fixText = false,
``
To:
``
fixText = true,
``
Nothing changes. It should move the textcoords but it does not, they stay where they are.

**Comment by BerkieBb** [comment]
It's fixed with [this PR](https://github.com/qbcore-framework/qb-doorlock/pull/79)
