### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Andyauk** [qbcore-framework/qb-doorlock#86]
this has been fine for weeks, now i get this message when i make a door, ?

`[  script:qb-doorlock] SCRIPT ERROR: @qb-doorlock/server/main.lua:227: /home/server/resources/[custom]/qb-doorlock/configs/testing.lua: Permission denied`

edit, i think it was something to do with the permissions of the files, myside.

**Comment by BerkieBb** [comment]
It seems like the server can't create a file for you because it has no permission to create it
