### ISSUE TITLE
[BUG] Casino Doors

### ISSUE THREAD

**Issue by BrandonSnippets** [qbcore-framework/qb-doorlock#88]
Hello guys im reporting a issue with qb-door lock. Everything is working fine tell I try to add lock door at the casino. I tried different doors with the same out come. When using /newdoor and add a door at the casino it does not save/accept the door. I provided a video of the issue. I have no errors client/server side. 

Video of what im talking about: https://streamable.com/0j5qav

**Comment by TonybynMp4** [comment]
stop qb-blackjack, it does weird shit and make that happen
you should be fine then :)
