### ISSUE TITLE
Option to make door stay open

### ISSUE THREAD

**Issue by CodeRedDev** [qbcore-framework/qb-doorlock#92]
An option to make a door stay open in the unlocked state would be great.
I don't know if this would benefit all door types but for example garages would benefit from this option.

This way they could be used like real world garages that don't just close up on you when you leave the area.

**Comment by Sinistermind81** [comment]
I agree, this would be a great feature to add!!!

**Comment by CptAllen** [comment]
config doorlist locked = false ?

**Comment by CodeRedDev** [comment]
> config doorlist locked = false ?

That just tells the plugin that the door is unlocked by default.

The feature requested here is that the (garage) door stays in open position.
