### ISSUE TITLE
updatestate

### ISSUE THREAD

**Issue by KingRyuShin** [qbcore-framework/qb-doorlock#94]
I'm using this trigger on my client.lua but it doesn't update the door.
`TriggerServerEvent('qb-doorlock:server:updateState', Config.Bobcat[doors].thermite[index].doorId, false, false, false, false)`
yes the doorid is returned correctly, i checked with print()..
but even if i remove the 
`Config.Bobcat[doors].thermite[index].doorId`
and write the door number, it still doesn't update it and it stay locked.

Here is the door code in qb-doorlock

`Config.DoorList['bobcat-door1'] = {
    authorizedJobs = { ['police'] = 0 },
    doorRate = 1.0,
    distance = 2.0,
    doors = {
        {objName = -1259801187, objYaw = 355.0022277832, objCoords = vec3(883.480347, -2258.529785, 32.534859)},
        {objName = -1563799200, objYaw = 175.0022277832, objCoords = vec3(880.895142, -2258.308350, 32.534859)}
    },
    doorLabel = 'Door1',
    locked = true,
    pickable = false,
    doorType = 'double',
}`

BUT, if i set myself to police job and thermite the door, i get the updatestate correctly

**Comment by BerkieBb** [comment]
Your door id is not a number, it's string
